# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: '3.10'
  post_build:
    - find _build/pdf -type f ! -name '*.pdf' -delete

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Python requirements for building documentation
python:
  install:
    - requirements: docs/requirements.txt

# Additional configuration
submodules:
  include:
    - all

# Add this section to specify the only file to upload for PDF
artifacts:
  - path: _build/pdf/squadds.pdf
    type: pdf
